namespace DiiL.Serene.Aoc {
    export interface RewardMonthyStatisticalRow {
        Id?: number;
        UserId?: number;
        PlatformProviderId?: number;
        PolicyId?: number;
        TaskId?: number;
        Month?: number;
        Year?: number;
        MonthAndYear?: string;
        ShopGradeId?: number;
        TotalAmountRatio?: string;
        TotalAmount?: number;
        TotalRewardMoney?: number;
        SmAomout?: number;
        SmAomoutRatio?: string;
        SmRewardMoney?: number;
        TvAmount?: number;
        TvAmountRatio?: string;
        TvRewardMoney?: number;
        RealShopAppearanceScore?: number;
        RealShopAppearanceRewardMoney?: number;
        StatisticalTime?: string;
        StatisticalRemark?: string;
        FinalPolicyMoney?: number;
        FinalSumMoney?: number;
        FinalMaxMoney?: number;
        AreaManagerId?: number;
        UserSpecialAward?: number;
        PlatformSpecialAward?: number;
        SpecialAmountRate?: string;
        SpecialAmount?: number;
        ScoreOfMonth?: number;
        ScoreOfMonthRatio?: string;
        RecognizedAmount?: number;
        IsReceivedConfirmation?: boolean;
        IsConfirmPrototypeAmountunt?: boolean;
        IsConfirmSpecialAmount?: boolean;
        IsConfirmBrandAmount?: boolean;
        GdpAmountRatio?: string;
        GdpAmount?: number;
        GdpRewardMoney?: number;
        ScoreRewardMoney?: number;
        TenantId?: number;
        UserShopId?: string;
        UserUserName?: string;
        UserPassword?: string;
        UserPlatformProviderManagerId?: number;
        UserPlatformProviderManagerUserName?: string;
        UserAreaManagerId?: number;
        UserAreaManagerUserName?: string;
        UserAddrProvinceId?: number;
        UserAddrProvince?: string;
        UserAddrCityId?: number;
        UserAddrCity?: string;
        UserAddrDistrictId?: number;
        UserAddrDistrict?: string;
        UserAddrTown?: string;
        UserAddrStreet?: string;
        UserAddrDetail?: string;
        UserGender?: boolean;
        UserIdCardNumber?: string;
        UserName?: string;
        UserMobilePhoneNumber?: string;
        UserTelePhoneNumber?: string;
        UserEmail?: string;
        UserCreateTime?: string;
        UserLastLoginTime?: string;
        UserIsNew?: boolean;
        UserIsRealShop?: boolean;
        UserIsStreetShop?: boolean;
        UserUserStatus?: string;
        UserShopStatus?: string;
        UserShopName?: string;
        UserCompanyName?: string;
        UserShopExpiredTime?: string;
        UserShopOpenTime?: string;
        UserShopCloseTime?: string;
        UserOnlineShopUrl?: string;
        UserScoreOfTotal?: number;
        UserScoreOfPunish?: number;
        UserScoreOfExchange?: number;
        UserScoreOfRemain?: number;
        UserIsFirstAgreement?: boolean;
        UserLanhaifuzeren?: string;
        UserTenantId?: number;
        TenantName?: string;
    }

    export namespace RewardMonthyStatisticalRow {
        export const idProperty = 'Id';
        export const nameProperty = 'MonthAndYear';
        export const localTextPrefix = 'Aoc.RewardMonthyStatistical';

        export namespace Fields {
            export declare const Id: string;
            export declare const UserId: string;
            export declare const PlatformProviderId: string;
            export declare const PolicyId: string;
            export declare const TaskId: string;
            export declare const Month: string;
            export declare const Year: string;
            export declare const MonthAndYear: string;
            export declare const ShopGradeId: string;
            export declare const TotalAmountRatio: string;
            export declare const TotalAmount: string;
            export declare const TotalRewardMoney: string;
            export declare const SmAomout: string;
            export declare const SmAomoutRatio: string;
            export declare const SmRewardMoney: string;
            export declare const TvAmount: string;
            export declare const TvAmountRatio: string;
            export declare const TvRewardMoney: string;
            export declare const RealShopAppearanceScore: string;
            export declare const RealShopAppearanceRewardMoney: string;
            export declare const StatisticalTime: string;
            export declare const StatisticalRemark: string;
            export declare const FinalPolicyMoney: string;
            export declare const FinalSumMoney: string;
            export declare const FinalMaxMoney: string;
            export declare const AreaManagerId: string;
            export declare const UserSpecialAward: string;
            export declare const PlatformSpecialAward: string;
            export declare const SpecialAmountRate: string;
            export declare const SpecialAmount: string;
            export declare const ScoreOfMonth: string;
            export declare const ScoreOfMonthRatio: string;
            export declare const RecognizedAmount: string;
            export declare const IsReceivedConfirmation: string;
            export declare const IsConfirmPrototypeAmountunt: string;
            export declare const IsConfirmSpecialAmount: string;
            export declare const IsConfirmBrandAmount: string;
            export declare const GdpAmountRatio: string;
            export declare const GdpAmount: string;
            export declare const GdpRewardMoney: string;
            export declare const ScoreRewardMoney: string;
            export declare const TenantId: string;
            export declare const UserShopId: string;
            export declare const UserUserName: string;
            export declare const UserPassword: string;
            export declare const UserPlatformProviderManagerId: string;
            export declare const UserPlatformProviderManagerUserName: string;
            export declare const UserAreaManagerId: string;
            export declare const UserAreaManagerUserName: string;
            export declare const UserAddrProvinceId: string;
            export declare const UserAddrProvince: string;
            export declare const UserAddrCityId: string;
            export declare const UserAddrCity: string;
            export declare const UserAddrDistrictId: string;
            export declare const UserAddrDistrict: string;
            export declare const UserAddrTown: string;
            export declare const UserAddrStreet: string;
            export declare const UserAddrDetail: string;
            export declare const UserGender: string;
            export declare const UserIdCardNumber: string;
            export declare const UserName: string;
            export declare const UserMobilePhoneNumber: string;
            export declare const UserTelePhoneNumber: string;
            export declare const UserEmail: string;
            export declare const UserCreateTime: string;
            export declare const UserLastLoginTime: string;
            export declare const UserIsNew: string;
            export declare const UserIsRealShop: string;
            export declare const UserIsStreetShop: string;
            export declare const UserUserStatus: string;
            export declare const UserShopStatus: string;
            export declare const UserShopName: string;
            export declare const UserCompanyName: string;
            export declare const UserShopExpiredTime: string;
            export declare const UserShopOpenTime: string;
            export declare const UserShopCloseTime: string;
            export declare const UserOnlineShopUrl: string;
            export declare const UserScoreOfTotal: string;
            export declare const UserScoreOfPunish: string;
            export declare const UserScoreOfExchange: string;
            export declare const UserScoreOfRemain: string;
            export declare const UserIsFirstAgreement: string;
            export declare const UserLanhaifuzeren: string;
            export declare const UserTenantId: string;
            export declare const TenantName: string;
        }

        ['Id', 'UserId', 'PlatformProviderId', 'PolicyId', 'TaskId', 'Month', 'Year', 'MonthAndYear', 'ShopGradeId', 'TotalAmountRatio', 'TotalAmount', 'TotalRewardMoney', 'SmAomout', 'SmAomoutRatio', 'SmRewardMoney', 'TvAmount', 'TvAmountRatio', 'TvRewardMoney', 'RealShopAppearanceScore', 'RealShopAppearanceRewardMoney', 'StatisticalTime', 'StatisticalRemark', 'FinalPolicyMoney', 'FinalSumMoney', 'FinalMaxMoney', 'AreaManagerId', 'UserSpecialAward', 'PlatformSpecialAward', 'SpecialAmountRate', 'SpecialAmount', 'ScoreOfMonth', 'ScoreOfMonthRatio', 'RecognizedAmount', 'IsReceivedConfirmation', 'IsConfirmPrototypeAmountunt', 'IsConfirmSpecialAmount', 'IsConfirmBrandAmount', 'GdpAmountRatio', 'GdpAmount', 'GdpRewardMoney', 'ScoreRewardMoney', 'TenantId', 'UserShopId', 'UserUserName', 'UserPassword', 'UserPlatformProviderManagerId', 'UserPlatformProviderManagerUserName', 'UserAreaManagerId', 'UserAreaManagerUserName', 'UserAddrProvinceId', 'UserAddrProvince', 'UserAddrCityId', 'UserAddrCity', 'UserAddrDistrictId', 'UserAddrDistrict', 'UserAddrTown', 'UserAddrStreet', 'UserAddrDetail', 'UserGender', 'UserIdCardNumber', 'UserName', 'UserMobilePhoneNumber', 'UserTelePhoneNumber', 'UserEmail', 'UserCreateTime', 'UserLastLoginTime', 'UserIsNew', 'UserIsRealShop', 'UserIsStreetShop', 'UserUserStatus', 'UserShopStatus', 'UserShopName', 'UserCompanyName', 'UserShopExpiredTime', 'UserShopOpenTime', 'UserShopCloseTime', 'UserOnlineShopUrl', 'UserScoreOfTotal', 'UserScoreOfPunish', 'UserScoreOfExchange', 'UserScoreOfRemain', 'UserIsFirstAgreement', 'UserLanhaifuzeren', 'UserTenantId', 'TenantName'].forEach(x => (<any>Fields)[x] = x);
    }
}

